language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t ravi/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true ravi/react-test npm test

after_success:
 - docker build -t ravi6682/multi-client ./client
 - docker build -t ravi6682/multi-nginx ./nginx
 - docker build -t ravi6682/multi-server ./server
 - docker build -t ravi6682/multi-worker ./worker

# Login into the Docker CLI
 - echo "DOCKER_ID"
 - echo "DOCKER_PASSWORD"
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# These images push to Docker-hub
 - docker push ravi6682/multi-client
 - docker push ravi6682/multi-nginx
 - docker push ravi6682/multi-server
 - docker push ravi6682/multi-worker